import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Agent } from "./agents.js";
import { MANAGED_HEADER_MD } from "./managed.js";

export interface AgentsMdInput {
  targetDir: string;
  agents: Agent[];
}

/**
 * Emit `<target>/AGENTS.md` — vendor-neutral description of the project,
 * its agent roster, and the important file conventions. Consumed by any
 * `AGENTS.md`-aware agent (Sourcegraph Cody, Aider, etc.).
 */
export async function writeAgentsMd(input: AgentsMdInput): Promise<string> {
  const { targetDir, agents } = input;
  const projectMeta = await readProjectMeta(targetDir);
  const path = join(targetDir, "AGENTS.md");
  const content = buildAgentsMd(projectMeta, agents);
  await writeFile(path, content, "utf8");
  return path;
}

interface ProjectMeta {
  name: string;
  slug: string;
}

async function readProjectMeta(targetDir: string): Promise<ProjectMeta> {
  try {
    const yaml = await readFile(join(targetDir, "coldpress.yaml"), "utf8");
    const name = /^\s*name:\s*"([^"]*)"/m.exec(yaml)?.[1] ?? "Unnamed Project";
    const slug = /^\s*slug:\s*"([^"]*)"/m.exec(yaml)?.[1] ?? "project";
    return { name, slug };
  } catch {
    return { name: "Unnamed Project", slug: "project" };
  }
}

function buildAgentsMd(meta: ProjectMeta, agents: Agent[]): string {
  const lines: string[] = [];
  lines.push(MANAGED_HEADER_MD);
  lines.push("");
  lines.push(`# AGENTS.md — ${meta.name}`);
  lines.push("");
  lines.push(
    "> Generated by coldpress-os (`coldpress init` / `coldpress update`). " +
      "See `CLAUDE.md` for the canonical project entry point.",
  );
  lines.push("");

  lines.push("## Project");
  lines.push("");
  lines.push(`- Name: ${meta.name}`);
  lines.push(`- Slug: ${meta.slug}`);
  lines.push("- Framework: [coldpress-os](https://github.com/coldpress-labs/coldpress-os) — 11-phase Shape A AI-native lifecycle.");
  lines.push("");

  lines.push("## Subagents");
  lines.push("");
  lines.push(
    "coldpress-os defines specialised subagents. Each runs with its own context window, tool allowlist, and model. Canonical definitions live at `.claude/agents/<name>.md`.",
  );
  lines.push("");
  lines.push("| Subagent | Model | Tools |");
  lines.push("|----------|-------|-------|");
  for (const agent of agents) {
    const tools = agent.tools.length ? agent.tools.join(", ") : "—";
    lines.push(`| \`${agent.name}\` | ${agent.model} | ${tools} |`);
  }
  lines.push("");

  lines.push("## Project conventions");
  lines.push("");
  lines.push("- **Sacred documents** live under `_context/sacred/` (context, tech-stack, PRD, architecture — the lite lane collapses these to one `spec.md`). Do not edit directly — use the change workflows in `coldpress-os/governance/`.");
  lines.push("- **Produced artefacts** go under `_context/{planning,design,implementation,testing,tracking,handoffs,audit}/`.");
  lines.push("- **Inputs** go under `_input/{raw,legacy,reference,vendor,assets}/`.");
  lines.push("- **Secrets** never commit. Declare shape in `secure/manifest.yaml`, put values in `secure/.env*` (git-ignored). See `docs/secure-pattern.md`.");
  lines.push("- **Runtime state** (EventStream run-logs, caches) lives under `.coldpress/` — git-ignored.");
  lines.push("");

  lines.push("## Framework location");
  lines.push("");
  lines.push("- `coldpress-os/` — framework files (lifecycle phases, skills, governance, data assets). Read-only; upgrade via `coldpress update`.");
  lines.push("- `.claude/agents/` — active subagent definitions (this project's copy).");
  lines.push("- `.claude/settings.json` — auto-enables the coldpress skill **plugin** (`coldpress-os/plugin/`); skills ship via the plugin, not per-skill wrappers.");
  lines.push("");

  return lines.join("\n") + "\n";
}
