import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { stringify } from "yaml";
import type { Agent } from "./agents.js";
import { MANAGED_HEADER_YAML } from "./managed.js";
import { claudeToolsToRooGroups } from "./tool-map.js";

export interface RoomodesInput {
  targetDir: string;
  agents: Agent[];
}

/**
 * Emit `<target>/.roomodes` — a YAML file of `customModes[]` usable by
 * Roo / Kilo. Tools are translated via `tool-map` into Roo's groups model.
 */
export async function writeRoomodes({ targetDir, agents }: RoomodesInput): Promise<string> {
  const path = join(targetDir, ".roomodes");

  const doc = {
    customModes: agents.map((agent) => ({
      slug: agent.name,
      name: titleCase(agent.name),
      roleDefinition: agent.systemPrompt,
      groups: claudeToolsToRooGroups(agent.tools),
    })),
  };

  const body = stringify(doc, { lineWidth: 0, blockQuote: "literal" });
  const content = `${MANAGED_HEADER_YAML}\n# Generated by \`coldpress init\` / \`coldpress update\`.\n\n${body}`;

  await writeFile(path, content, "utf8");
  return path;
}

function titleCase(slug: string): string {
  return slug
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
