/**
 * `build:client-touchpoints` — regenerate `docs/generated/client-touchpoints.md`
 * from `data/client-touchpoints.yaml` (WS9-D, §7.17). The client-facing rhythm as
 * a generated table, drift-checked — one source, generated view.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { packageRoot } from "../utils/paths.js";

const SRC = join(packageRoot, "data/client-touchpoints.yaml");
const OUT_DIR = join(packageRoot, "docs/generated");
const OUT = join(OUT_DIR, "client-touchpoints.md");

interface Touchpoint {
  phase: number;
  touchpoint: string;
  produced_by: string;
  artifact: string;
}

export function buildClientTouchpoints(): string {
  const data = parseYaml(readFileSync(SRC, "utf8")) as { touchpoints?: Touchpoint[] };
  const rows = (data.touchpoints ?? [])
    .slice()
    .sort((a, b) => a.phase - b.phase)
    .map((t) => `| ${t.phase} | ${t.touchpoint} | \`${t.produced_by}\` | ${t.artifact} |`);

  return (
    `# Client touchpoints registry\n\n` +
    `> GENERATED by \`npm run build:client-touchpoints\` from \`data/client-touchpoints.yaml\`.\n` +
    `> Do not hand-edit — run the generator and commit. The client-facing rhythm made as\n` +
    `> mechanical as the internal gates (§7.17): the client is part of the lifecycle.\n\n` +
    `| Phase | Touchpoint | Produced by | Client-facing artifact |\n` +
    `|---|---|---|---|\n` +
    `${rows.join("\n")}\n`
  );
}

if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
const md = buildClientTouchpoints();
writeFileSync(OUT, md, "utf8");
process.stdout.write(`client-touchpoints.md: ${(parseYaml(readFileSync(SRC, "utf8")) as { touchpoints?: unknown[] }).touchpoints?.length ?? 0} touchpoints\n`);
