/**
 * `build:deploy-matrix` — regenerate `docs/generated/stack-deploy-matrix.md`
 * from every deploy pack's `compatible_stacks` × the stack packs (WS6-F, §9 WS6).
 *
 * `deploy-select` (Phase 3) consults this matrix to offer only deploy packs
 * compatible with the locked stack and warn on unsupported pairs. One source
 * (the packs), generated view — drift-checked by `check:drift`.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { packageRoot } from "../utils/paths.js";

const DEPLOY_PACKS_DIR = join(packageRoot, "data/deploy-packs");
const STACK_PACKS_DIR = join(packageRoot, "skills/stack-packs");
const OUT_DIR = join(packageRoot, "docs/generated");
const OUT_PATH = join(OUT_DIR, "stack-deploy-matrix.md");

function dirs(root: string): string[] {
  try {
    return readdirSync(root, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort();
  } catch {
    return [];
  }
}

interface DeployPackInfo {
  name: string;
  platform: string;
  compatible: Set<string>;
}

function readDeployPacks(): DeployPackInfo[] {
  return dirs(DEPLOY_PACKS_DIR).map((name) => {
    const raw = parseYaml(readFileSync(join(DEPLOY_PACKS_DIR, name, "pack.yaml"), "utf8")) as {
      name?: string;
      platform?: string;
      compatible_stacks?: string[];
    };
    return {
      name: raw.name ?? name,
      platform: raw.platform ?? name,
      compatible: new Set(raw.compatible_stacks ?? []),
    };
  });
}

/** Build the matrix markdown from the packs. */
export function buildDeployMatrix(): string {
  const deployPacks = readDeployPacks();
  const stackPacks = dirs(STACK_PACKS_DIR);

  const header = ["| stack pack ↓ / deploy pack → |", ...deployPacks.map((d) => ` ${d.name} |`)].join("");
  const sep = ["|---|", ...deployPacks.map(() => "---|")].join("");
  const rows = stackPacks.map((stack) => {
    const cells = deployPacks.map((d) => (d.compatible.has(stack) ? " ✓ |" : " · |"));
    return [`| \`${stack}\` |`, ...cells].join("");
  });

  const unsupported = stackPacks.filter((s) => !deployPacks.some((d) => d.compatible.has(s)));

  return (
    `# Stack × Deploy compatibility matrix\n\n` +
    `> GENERATED by \`npm run build:deploy-matrix\` from every \`data/deploy-packs/*/pack.yaml\`'s\n` +
    `> \`compatible_stacks\`. Do not hand-edit — run the generator and commit. \`deploy-select\` (Phase 3)\n` +
    `> reads this to offer only compatible packs and warn on unsupported pairs.\n\n` +
    `Platforms: ${deployPacks.map((d) => `**${d.name}** (${d.platform})`).join(" · ")}\n\n` +
    `${header}\n${sep}\n${rows.join("\n")}\n\n` +
    `**Legend:** ✓ supported · · not supported.\n\n` +
    (unsupported.length
      ? `**No web-deploy pack** for: ${unsupported.map((s) => `\`${s}\``).join(", ")} ` +
        `— these ship elsewhere (npm packages, browser stores) or are capability packs, not web-deploy targets.\n`
      : ``)
  );
}

// Run directly (via `tsx`): write the file.
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });
const md = buildDeployMatrix();
writeFileSync(OUT_PATH, md, "utf8");
process.stdout.write(
  `stack-deploy-matrix.md: ${readDeployPacks().length} deploy packs × ${dirs(STACK_PACKS_DIR).length} stack packs\n`,
);
