/**
 * EventStream schema (§6.4).
 *
 * Ports OpenHands' append-only event-log pattern as coldpress-os's
 * execution-trace representation. Complements (does not replace) the
 * DAG plan. Persisted at `.coldpress/runs/<run-id>/events.jsonl`.
 *
 * Two event families:
 *   - Actions       — things the orchestrator DOES
 *   - Observations  — results / responses to actions
 *
 * Plus a `Condensation` meta-event emitted at wave boundaries, turning
 * each wave's exit summary into a first-class trace event rather than
 * implicit context compaction.
 *
 * Design invariants:
 *   - `seq` is a monotonic, strictly increasing integer per run. No
 *     holes; no duplicates. Writer enforces.
 *   - `timestamp` is ISO-8601.
 *   - `run_id` is a kebab-case slug (generator ensures uniqueness by
 *     embedding a timestamp prefix).
 *   - Observation events carry `cause_seq` pointing at the `seq` of the
 *     originating Action — lets readers reconstruct request/response
 *     pairs without inferring from adjacency.
 *
 * Not exposed to the LLM directly per plan §6.4 — purely for debugging,
 * replay, gate evaluation, and the Project Dashboard (§6.10) Stats tab.
 */

import { z } from "zod";

const TIMESTAMP = z.string().datetime();
const SEQ = z.number().int().nonnegative();
const RUN_ID = z
  .string()
  .min(1)
  .regex(
    /^[a-z0-9][a-z0-9-]*$/,
    "run_id must be a kebab-case slug (generated by makeRunId)",
  );
const SKILL_ID = z.string().min(1);
const GATE_ID = z.string().min(1);
const WAVE_ID = z.string().min(1);
// Shape A = 11 phases (was max 9 pre-Shape-A; widened in v0.4 WS1 — the
// run-log hook records phases up to 11). Widening only; existing events valid.
const PHASE = z.number().int().min(1).max(11);

const BASE = {
  schema_version: z.literal(1),
  seq: SEQ,
  run_id: RUN_ID,
  timestamp: TIMESTAMP,
};

// ─── Action events ────────────────────────────────────────────────

export const WaveStartActionSchema = z.object({
  ...BASE,
  kind: z.literal("wave-start"),
  wave_id: WAVE_ID,
  phase: PHASE,
  label: z.string().optional(),
});

export const WaveEndActionSchema = z.object({
  ...BASE,
  kind: z.literal("wave-end"),
  wave_id: WAVE_ID,
  phase: PHASE,
  status: z.enum(["success", "failure", "interrupted"]),
  duration_ms: z.number().int().nonnegative().optional(),
});

export const SkillInvokeActionSchema = z.object({
  ...BASE,
  kind: z.literal("skill-invoke"),
  skill_id: SKILL_ID,
  /**
   * What triggered this skill: usually a subagent slug (`pm`,
   * `architect`, etc.) or the orchestrator itself (`orchestrator`).
   */
  caller: z.string().optional(),
  /**
   * Optional free-form args dictionary. Orchestrator MAY choose to
   * elide sensitive values — the EventStream is persisted to disk
   * and grep-able.
   */
  args: z.record(z.string(), z.unknown()).optional(),
});

export const GateEvaluateActionSchema = z.object({
  ...BASE,
  kind: z.literal("gate-evaluate"),
  gate_id: GATE_ID,
  phase: PHASE,
});

// ─── Observation events ───────────────────────────────────────────

const CAUSE_SEQ_OPTIONAL = SEQ.optional();

export const SkillResultObservationSchema = z.object({
  ...BASE,
  kind: z.literal("skill-result"),
  skill_id: SKILL_ID,
  cause_seq: CAUSE_SEQ_OPTIONAL,
  exit_code: z.number().int(),
  duration_ms: z.number().int().nonnegative().optional(),
  /** Path to the primary artefact the skill produced, if any. */
  artifact_path: z.string().optional(),
  message: z.string().optional(),
});

export const GatePassObservationSchema = z.object({
  ...BASE,
  kind: z.literal("gate-pass"),
  gate_id: GATE_ID,
  phase: PHASE,
  cause_seq: CAUSE_SEQ_OPTIONAL,
});

export const GateFailObservationSchema = z.object({
  ...BASE,
  kind: z.literal("gate-fail"),
  gate_id: GATE_ID,
  phase: PHASE,
  cause_seq: CAUSE_SEQ_OPTIONAL,
  blockers: z.array(z.string()),
});

// ─── Meta event ───────────────────────────────────────────────────

export const CondensationSchema = z.object({
  ...BASE,
  kind: z.literal("condensation"),
  wave_id: WAVE_ID,
  summary: z.string().min(1),
  /** Inclusive range of seq ids this condensation covers. */
  from_seq: SEQ,
  to_seq: SEQ,
});

/** Token usage where the runtime exposes it (WS7 §4.8 — "tokens where exposed"). */
export const TokenUsageSchema = z
  .object({
    input: z.number().int().nonnegative(),
    output: z.number().int().nonnegative(),
    total: z.number().int().nonnegative(),
  })
  .partial();
export type TokenUsage = z.infer<typeof TokenUsageSchema>;

/**
 * Session boundary observation — emitted by the `run-log` hook (WS1, §4.4) on
 * Stop / SubagentStop, so every run captures its arc for the evolution loop.
 * WS7 (§4.8) enriches with `model` + `tokens` (where exposed) + taxonomy tags;
 * gate results are captured as their own `gate-pass`/`gate-fail` events.
 */
export const SessionBoundaryObservationSchema = z.object({
  ...BASE,
  kind: z.literal("session-boundary"),
  boundary: z.enum(["stop", "subagent-stop"]),
  /** Dispatching agent slug (subagent) or "butler" for the main session. */
  agent: z.string().optional(),
  phase: PHASE.optional(),
  lane: z.enum(["lite", "full"]).optional(),
  duration_ms: z.number().int().nonnegative().optional(),
  /** Model that ran the session, where the runtime exposes it (WS7). */
  model: z.string().optional(),
  /** Token usage, where exposed (WS7). Feeds `evolve`'s cost leaderboard. */
  tokens: TokenUsageSchema.optional(),
  /** Failure taxonomy tags (WS7 loop). */
  taxonomy_tags: z.array(z.string()).optional(),
});

// ─── Discriminated union ──────────────────────────────────────────

export const EventSchema = z.discriminatedUnion("kind", [
  WaveStartActionSchema,
  WaveEndActionSchema,
  SkillInvokeActionSchema,
  GateEvaluateActionSchema,
  SkillResultObservationSchema,
  GatePassObservationSchema,
  GateFailObservationSchema,
  CondensationSchema,
  SessionBoundaryObservationSchema,
]);

export type Event = z.infer<typeof EventSchema>;
export type WaveStartAction = z.infer<typeof WaveStartActionSchema>;
export type WaveEndAction = z.infer<typeof WaveEndActionSchema>;
export type SkillInvokeAction = z.infer<typeof SkillInvokeActionSchema>;
export type SkillResultObservation = z.infer<typeof SkillResultObservationSchema>;
export type GateEvaluateAction = z.infer<typeof GateEvaluateActionSchema>;
export type GatePassObservation = z.infer<typeof GatePassObservationSchema>;
export type GateFailObservation = z.infer<typeof GateFailObservationSchema>;
export type Condensation = z.infer<typeof CondensationSchema>;
export type SessionBoundaryObservation = z.infer<typeof SessionBoundaryObservationSchema>;

/** Input shape for `EventStreamWriter.append()` — writer fills the base fields. */
export type EventInput = {
  [K in Event["kind"]]: Omit<
    Extract<Event, { kind: K }>,
    "schema_version" | "seq" | "run_id" | "timestamp"
  >;
}[Event["kind"]];

/**
 * Generate a monotonic kebab-case run id: `run-YYYYMMDD-HHMMSS-<rand>`.
 * Lexicographic sort matches chronological order. 6-char suffix de-collides
 * within-second concurrent starts.
 */
export function makeRunId(now: Date = new Date()): string {
  const pad = (n: number, w = 2) => String(n).padStart(w, "0");
  const y = now.getUTCFullYear();
  const m = pad(now.getUTCMonth() + 1);
  const d = pad(now.getUTCDate());
  const hh = pad(now.getUTCHours());
  const mm = pad(now.getUTCMinutes());
  const ss = pad(now.getUTCSeconds());
  const rand = Math.floor(Math.random() * 0xffffff)
    .toString(16)
    .padStart(6, "0");
  return `run-${y}${m}${d}-${hh}${mm}${ss}-${rand}`;
}
