/**
 * `tokens-build` (§5 P5) — generate the code binding from `tokens.json`.
 *
 * Emits CSS custom properties so the build consumes tokens *by construction*: a
 * token edit re-generates the CSS with no manual code change, making divergence
 * impossible rather than merely detectable. Color roles with a `dark` value get a
 * `prefers-color-scheme: dark` override. (Framework config — Tailwind theme, etc.
 * — is a per-stack-pack extension of this same source.)
 */

import type { Tokens } from "../../schemas/design/tokens.schema.js";

/** Render a dimension token: a number becomes `<n>px`; a string passes through. */
function dim(v: string | number): string {
  return typeof v === "number" ? `${v}px` : v;
}

function block(vars: [string, string][], indent = "  "): string {
  return vars.map(([k, v]) => `${indent}${k}: ${v};`).join("\n");
}

/** Generate the CSS custom-property binding from validated tokens. */
export function buildCss(tokens: Tokens): string {
  const root: [string, string][] = [];
  const dark: [string, string][] = [];

  for (const [role, family] of Object.entries(tokens.typography.families)) root.push([`--font-${role}`, family]);
  for (const [key, size] of Object.entries(tokens.typography.sizes)) root.push([`--text-${key}`, dim(size)]);
  for (const [key, w] of Object.entries(tokens.typography.weights ?? {})) root.push([`--weight-${key}`, String(w)]);
  for (const [key, lh] of Object.entries(tokens.typography.line_heights ?? {})) root.push([`--leading-${key}`, dim(lh)]);

  for (const [role, val] of Object.entries(tokens.color.roles)) {
    root.push([`--color-${role}`, val.light]);
    if (val.dark) dark.push([`--color-${role}`, val.dark]);
  }
  for (const [key, hex] of Object.entries(tokens.color.palette ?? {})) root.push([`--palette-${key}`, hex]);

  for (const [key, v] of Object.entries(tokens.spacing)) root.push([`--space-${key}`, dim(v)]);
  for (const [key, v] of Object.entries(tokens.radii ?? {})) root.push([`--radius-${key}`, dim(v)]);
  for (const [key, v] of Object.entries(tokens.shadows ?? {})) root.push([`--shadow-${key}`, v]);
  for (const [key, v] of Object.entries(tokens.breakpoints ?? {})) root.push([`--bp-${key}`, dim(v)]);
  for (const [key, v] of Object.entries(tokens.z_index ?? {})) root.push([`--z-${key}`, String(v)]);
  for (const [key, v] of Object.entries(tokens.motion?.durations ?? {})) root.push([`--duration-${key}`, dim(v)]);
  for (const [key, v] of Object.entries(tokens.motion?.easings ?? {})) root.push([`--ease-${key}`, v]);

  const lines = [
    "/* GENERATED by `coldpress tokens build` from _context/design/tokens.json — do not edit by hand. */",
    ":root {",
    block(root),
    "}",
  ];
  if (dark.length > 0) {
    lines.push("", "@media (prefers-color-scheme: dark) {", "  :root {", block(dark, "    "), "  }", "}");
  }
  return lines.join("\n") + "\n";
}
